version: '3.6'

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
    - 1883:1883

  mosquitto_sub:
    image: eclipse-mosquitto
    command: mosquitto_sub -h mosquitto -v -t '#'
