apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
  - name: tcp-mqtt
    port: 1883
    targetPort: tcp-mqtt
